SKILL_REGISTRY = [
    "cbt_thought_record",
    "grounding_5_4_3_2_1",
    "sleep_hygiene",
    "post_crisis_check_in",
    "box_breathing",
    "mood_check_in",
    "behavioral_activation",
    "worry_time",
    "mi_readiness_ruler",
    "stop_technique",
    "progressive_muscle_relaxation",
    "safe_place_visualization",
    "dbt_tipp",
    "psychoed_anxiety",
    "psychoed_depression",
]
