"""Shared prod-probe harness — one implementation for the five prod-HTTP driver scripts
that each hand-rolled this (scripts/prod_smoke/verification_session.py,
scripts/prod_smoke/hr1_stage1_verify.py, scripts/prod_smoke/hr1_stage1_conformance.py,
scripts/safety/sf1_phase0_prod_http.py, scripts/bot_behaviour_audit/measure_layer1_prod_http.py).

Surface: DEFAULT_BASE_URL, TEST_USER, resolve_creds(), chat(), audit(), new_session_id().
Per-caller differences (SELECT column lists, session-id tag/prefix schemes, response-error
handling) stay at the call sites — this module only owns the mechanism.

Two ride-along defects fixed HERE (not yet in the five callers — they migrate later):

  1. Credential-off-argv: the five originals invoke `psql DATABASE_URL ...` — the full
     connection string, password included, as a positional argv token (visible to any
     `ps`/`/proc` reader on the host, and to shell history / process-launch logging).
     This module decomposes DATABASE_URL into libpq PG* environment variables (PGHOST,
     PGPORT, PGUSER, PGPASSWORD, PGDATABASE, PGSSLMODE) and invokes psql with NO conninfo
     argv token at all — psql falls back to the standard PG* env vars. The password never
     appears in argv or in a subprocess command line.

  2. Bound session-id: the five originals f-string the session_id straight into the SQL
     text (`f"... WHERE session_id='{sid}' ..."`). session_id is generated by this module
     from a caller-supplied tag, but that's still string-built SQL, not a proof against
     injection. `audit()` instead binds session_id via psql's `-v` variable mechanism and
     references it in the query as `:'sid'` (psql's quoted-literal substitution), the
     standard safe pattern for psql-driven scripting without a prepared-statement API.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import uuid
from dataclasses import dataclass, field
from typing import Optional
from urllib.parse import parse_qs, urlsplit

DEFAULT_BASE_URL = "https://sage-api-production-3328.up.railway.app"
TEST_USER = "7b382b90-b0be-4cca-93dc-12e07c0b30bb"  # in prod SAGE_TEST_USER_IDS -> tripwire muted

_RAILWAY_CALLER_TAG = "skill:use-railway@1.2.0"


# ─────────────────────────────────────────────────────────────────────────────
# Credentials
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class Creds:
    api_key: str
    database_url: str
    test_user_ids: str = ""
    raw: dict = field(default_factory=dict)


def resolve_creds(*, use_env: bool = True) -> Creds:
    """SAGE_API_KEY / DATABASE_URL from the environment if both are present (use_env=True,
    the default — every one of the five originals honors an env override); otherwise (or
    when use_env=False) shells out to `railway variables --json`, matching the pattern all
    five callers already use for the production project.

    The railway fallback is opt-in only: it pulls live prod credentials (a verification
    run once had this fallback fire silently and land those credentials in a session
    transcript). It runs ONLY when SAGE_ALLOW_RAILWAY_FALLBACK=1 is set in the env; otherwise,
    with env vars absent, this raises RuntimeError telling the operator to export
    SAGE_API_KEY/DATABASE_URL or set the gate var — never a silent live-credential pull.

    Once the railway fallback does run, a variable missing from `railway variables --json`
    raises immediately (fail-fast), naming the missing variable — it never silently
    resolves to an empty string, matching the original scripts' dict-indexing behavior.
    """
    if use_env:
        api_key = os.environ.get("SAGE_API_KEY")
        database_url = os.environ.get("DATABASE_URL")
        if api_key and database_url:
            return Creds(
                api_key=api_key,
                database_url=database_url,
                test_user_ids=os.environ.get("SAGE_TEST_USER_IDS", ""),
                raw={},
            )
    if os.environ.get("SAGE_ALLOW_RAILWAY_FALLBACK") != "1":
        raise RuntimeError(
            "resolve_creds(): SAGE_API_KEY / DATABASE_URL not both set in the environment, "
            "and the `railway variables` fallback is not opted in. Either export "
            "SAGE_API_KEY and DATABASE_URL yourself, or set SAGE_ALLOW_RAILWAY_FALLBACK=1 "
            "to allow this to shell out to `railway variables --json` and pull live prod "
            "credentials into this session."
        )
    env = {**os.environ, "RAILWAY_CALLER": _RAILWAY_CALLER_TAG}
    raw = json.loads(subprocess.check_output(["railway", "variables", "--json"], text=True, env=env))
    missing = [k for k in ("SAGE_API_KEY", "DATABASE_URL") if k not in raw]
    if missing:
        raise RuntimeError(
            f"resolve_creds(): `railway variables --json` did not return: {', '.join(missing)}. "
            "Check that the linked railway project/environment/service is correct."
        )
    return Creds(
        api_key=raw["SAGE_API_KEY"],
        database_url=raw["DATABASE_URL"],
        test_user_ids=raw.get("SAGE_TEST_USER_IDS", ""),
        raw=raw,
    )


# ─────────────────────────────────────────────────────────────────────────────
# chat() — drives the serving /chat HTTP surface
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class ChatResult:
    text: str                 # raw response body (empty string if the body couldn't be split out)
    message: str              # best-effort extracted reply text: json message/response, else raw body/stdout
    headers: dict              # lower-cased response header name -> value
    json: Optional[dict]      # parsed JSON body, or None if the body wasn't valid JSON
    status: int                # HTTP status code of the FINAL response (0 if missing/unparsable)
    returncode: int
    stderr: str


def _chat_body(session_id: str, text: str, user_id: str) -> str:
    return json.dumps({
        "messages": [{"role": "user", "content": text}],
        "session_id": session_id,
        "user_id": user_id,
    })


def _chat_argv(base_url: str, api_key: str, body: str, timeout: int) -> list:
    return [
        "curl", "-sS", "--max-time", str(timeout), "-i", "-X", "POST", f"{base_url}/chat",
        "-H", "Content-Type: application/json",
        "-H", f"X-Sage-Api-Key: {api_key}",
        "--data-binary", body,
    ]


def _split_headers_and_payload(raw: str) -> tuple:
    """Split curl -i output into (header_text of the FINAL header block, payload).

    curl -i emits one full "HTTP/... status line + headers" block per response it
    receives before the body — e.g. a redirect hop, or a 100-continue preamble ahead
    of a POST — each terminated by a blank line, all concatenated ahead of the actual
    body. Walking off leading blocks (as long as what remains still starts with
    "HTTP/") and keeping the last one found means header_text always reflects the
    response actually delivered to the caller, not an intermediate one.

    Returns ("", raw) if raw doesn't start with a header block at all (e.g. curl
    produced no output, or a transport failure left stdout empty/non-HTTP-shaped).
    """
    remaining = raw
    last_header_text = ""
    found_any = False
    # Theoretical edge: if the BODY itself happened to start with the literal text
    # "HTTP/" (e.g. a proxied response echoing raw HTTP text as its payload), this loop
    # would misread it as one more header block and keep consuming. Not something any
    # of the five callers' /chat JSON bodies do in practice; noted as a known limit.
    while remaining.startswith("HTTP/"):
        split_at = None
        for sep in ("\r\n\r\n", "\n\n"):
            idx = remaining.find(sep)
            if idx != -1 and (split_at is None or idx < split_at[0]):
                split_at = (idx, sep)
        if split_at is None:
            break
        idx, sep = split_at
        last_header_text = remaining[:idx]
        remaining = remaining[idx + len(sep):]
        found_any = True
    if not found_any:
        return "", raw
    return last_header_text, remaining


def _parse_status(header_text: str) -> int:
    """HTTP status code from the first line of a header block (e.g. 'HTTP/1.1 200 OK'
    or 'HTTP/2 404'). Returns 0 if header_text is empty or the status line is
    missing/unparsable — this never raises, callers treat 0 as "unknown/error"."""
    if not header_text:
        return 0
    lines = header_text.splitlines()
    if not lines:
        return 0
    m = re.match(r"^HTTP/\S+\s+(\d{3})", lines[0].strip())
    return int(m.group(1)) if m else 0


def chat(session_id: str, text: str, *, base_url: str = None, api_key: str = None,
          user_id: str = None, timeout: int = 70) -> ChatResult:
    """POST one turn to /chat. Returns headers + body so callers that need response
    headers (e.g. x-sage-crisis-flags) and callers that need the reply body/text both
    work off one HTTP call — no double-POST against a stateful session.

    api_key defaults to resolve_creds().api_key when not supplied; base_url defaults to
    DEFAULT_BASE_URL; user_id defaults to TEST_USER.
    """
    base_url = base_url or DEFAULT_BASE_URL
    if api_key is None:
        api_key = resolve_creds().api_key
    user_id = user_id or TEST_USER

    body = _chat_body(session_id, text, user_id)
    argv = _chat_argv(base_url, api_key, body, timeout)
    r = subprocess.run(argv, capture_output=True, text=True)

    header_text, payload = _split_headers_and_payload(r.stdout)
    status = _parse_status(header_text)
    headers = {}
    for line in header_text.splitlines()[1:]:  # [0] is the HTTP status line
        if ":" in line:
            k, v = line.split(":", 1)
            headers[k.strip().lower()] = v.strip()

    parsed = None
    if payload:
        try:
            parsed = json.loads(payload)
        except Exception:
            parsed = None

    message = None
    if isinstance(parsed, dict):
        message = parsed.get("message") or parsed.get("response")
    message = message or payload or r.stdout or r.stderr

    return ChatResult(text=payload, message=message, headers=headers, json=parsed,
                       status=status, returncode=r.returncode, stderr=r.stderr)


# ─────────────────────────────────────────────────────────────────────────────
# audit() — session_audit readback, credentials off argv, session-id bound not interpolated
# ─────────────────────────────────────────────────────────────────────────────

def _pg_env(database_url: str, base_env: dict = None) -> dict:
    """Decompose a postgres:// DSN into libpq PG* env vars. No component of the DSN
    (host, user, password, db, sslmode) is meant to reach argv from this point on —
    psql is invoked with no positional conninfo token and picks these up from env."""
    parts = urlsplit(database_url)
    env = dict(base_env if base_env is not None else os.environ)
    if parts.hostname:
        env["PGHOST"] = parts.hostname
    if parts.port:
        env["PGPORT"] = str(parts.port)
    if parts.username:
        env["PGUSER"] = parts.username
    if parts.password:
        env["PGPASSWORD"] = parts.password
    db = parts.path.lstrip("/")
    if db:
        env["PGDATABASE"] = db
    qs = parse_qs(parts.query)
    if "sslmode" in qs:
        env["PGSSLMODE"] = qs["sslmode"][0]
    return env


def _audit_query(columns: str, *, order_by: str = "turn_number DESC", limit: int = 1) -> str:
    return f"SELECT {columns} FROM session_audit WHERE session_id = :'sid' ORDER BY {order_by} LIMIT {limit};"


def _audit_argv(session_id: str, columns: str, *, order_by: str = "turn_number DESC", limit: int = 1) -> list:
    """The psql argv for one audit readback. No DATABASE_URL / password token — those
    live only in the env dict `_pg_env()` builds. session_id is bound via `-v sid=...`
    and referenced in the query text as `:'sid'` (psql's quoted-literal substitution),
    never spliced into the SQL string."""
    sql = _audit_query(columns, order_by=order_by, limit=limit)
    return ["psql", "-v", f"sid={session_id}", "-tAc", sql]


def audit(session_id: str, columns: str, *, database_url: str = None,
          order_by: str = "turn_number DESC", limit: int = 1) -> str:
    """Read back `columns` from the most recent session_audit row for session_id.
    Returns the raw stripped psql -tA output (caller parses per its own column list —
    e.g. split on '|' for a comma-separated SELECT, or take it whole for a caller that
    builds its own concatenated column expression)."""
    database_url = database_url or resolve_creds().database_url
    env = _pg_env(database_url)
    argv = _audit_argv(session_id, columns, order_by=order_by, limit=limit)
    r = subprocess.run(argv, capture_output=True, text=True, env=env)
    return r.stdout.strip()


# ─────────────────────────────────────────────────────────────────────────────
# new_session_id()
# ─────────────────────────────────────────────────────────────────────────────

def new_session_id(tag: str, *, n: int = 8) -> str:
    """`{tag}-{random hex}`. Callers own their own prefix/tag scheme (e.g.
    "prodsuite-run-med-ar", "sf1p0-{fixture_id}-{sample}") — this only owns the
    collision-avoiding random suffix. n=0 returns `tag` unchanged (for a caller that
    wants deterministic, non-random ids, e.g. a run-tag + row-index scheme)."""
    if n <= 0:
        return tag
    return f"{tag}-{uuid.uuid4().hex[:n]}"
